# -*- coding: utf-8 -*-
"""Volatividade .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UpK9wJKwiHKQYo2MH-jMHtdso-oFcr9a

#Volatividade das ações da B3 (últimos 10 anos)
"""

# Importar as bibliotecas
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns

# Definir o ticker da ação desejada
ticker = "PETR4.SA"

# Obter os dados históricos da ação, escolhendo a quantidades de anos desejada 
stock_data = yf.download(ticker, period="10y")

# Calcular a volatilidade anualizada
volatility = stock_data["Close"].pct_change().rolling(window=252).std() * (252 ** 0.5)

# Plotar o gráfico da volatilidade e editar os parametros (títulos, rótulos e estilo)
plt.figure(figsize=(12, 6))
sns.set_style("darkgrid")
sns.lineplot(data=volatility, linewidth=1.5, color="blue")
plt.title(f"Volatilidade anualizada de {ticker} nos últimos 10 anos", fontsize=16)
plt.xlabel("Data", fontsize=12)
plt.ylabel("Volatilidade (%)", fontsize=12)
plt.ylim(bottom=0)
plt.show()

